### ISSUE TITLE
Pagina met resultaten moet kaar zijn zodat realtime resultaten kunnen worden getoond.

### ISSUE THREAD

**Issue by Fekkes** [TeamSnowflake/StemApp-fieldtest#10]
Misschien handig om dit door iemand te laten doen die niet met de servers bezig is?

**Comment by Jimmy390** [comment]
Heb het nu werkend dat hij gerefreshed kan worden

**Comment by Jimmy390** [comment]
De resultaten pagina wordt nu om de 10 seconden gerefreshed, ik heb een script toegevoegd in de vote-view.html
