### ISSUE TITLE
Maken van een checklist voor testgebruikers, dit kan als basis dienen voor volgende fase.

### ISSUE THREAD

**Issue by Fekkes** [TeamSnowflake/StemApp-fieldtest#12]
Uitzoeken of dit gedaan moet worden voor ons testverslag.
Misschien dit ook toevoegen als issue in de StemApp-Documentatie repository?

**Comment by KevinH96** [comment]
N.a.v. gesprek met Patrick besloten om nieuwe issues die niet noodzakelijk zijn niet meer aan te nemen tijdens de duur van het project. Kan eventueel na 22-06-2018 wel overlegd worden, maar wordt voor nu even genegeerd,

**Comment by KevinH96** [comment]
N.a.v. gesprek met Patrick besloten om nieuwe issues die niet noodzakelijk zijn niet meer aan te nemen tijdens de duur van het project. Kan eventueel na 22-06-2018 wel overlegd worden, maar wordt voor nu even genegeerd,
