### ISSUE TITLE
Stemapp.ddns.net beveiligen met wachtwoord

### ISSUE THREAD

**Issue by Fekkes** [TeamSnowflake/StemApp-fieldtest#16]
# Situatie
Er is nu geen mogelijkheid om rollen te maken in onze omgeving. Het probleem wat hierdoor ontstaat is dat iedereen die de Me-App heeft stellingen kan aanmaken,verwijderen en aanpassen. Een tijdelijke fix hiervoor is dat de site stemapp.ddn.net beveiligd gaat worden met een wachtwoord.

**Comment by Jimmy390** [comment]
stemapp.ddns.net is nu beveiligd met een wachtwoord (deze is te vinden in onze lastpass)
