### ISSUE TITLE
Toevoegen aan team, schrijf rechten op deze repo

### ISSUE THREAD

**Issue by maxvisser** [TeamSnowflake/StemApp-fieldtest#4]
Kunnen jullie mij schrijf rechten geven? Zodat ik evt ook issues kan aanmaken en assignen? Wellicht ook voor jamalv en maartenfv

**Comment by KevinH96** [comment]
Ik heb zowel jou als Jamal een invite gestuurd en rechten gegeven. Maarten zit er al in :)
